// <auto-generated />
using System;
using GeoPetClient.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeoPetClient.Migrations
{
    [DbContext(typeof(GeoPetContext))]
    partial class GeoPetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("GeoPetClient.DataModels.Owner", b =>
                {
                    b.Property<string>("Mail")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.HasKey("Mail");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("GeoPetClient.DataModels.Pet", b =>
                {
                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Color");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsLost");

                    b.Property<string>("Race");

                    b.Property<string>("Type");

                    b.HasKey("Email", "Name");

                    b.ToTable("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
